# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Peter Henry
email: me@peterhenry.net
description: > # this means to ignore newlines until "baseurl:"
  My corner of the internet, where I write about my projects and other things that interest me.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://peterhenry.net" # the base hostname & protocol for your site
github_username:  mos_basik

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass

exclude: [vendor]